### ISSUE TITLE
Warning 106

### ISSUE THREAD

**Issue by Lopuch** [AgoraIO/Agora-C_Sharp-SDK#108]
Hello,
If I run the solution and select "1v1" video for example, I am still getting "OnWarning 106" and  "OnRejoinChannelSuccess" repeatedly.
I think the C# SDK does not work for me because when I join the same room in C# SDK and Web SDK, I am unable to see a strem from C# SDK on a web.

Am I missing something?
Thank you

**Comment by zhangtao1104** [comment]
Can you help to provide a special channel Name which reproduce this problem?

**Comment by Lopuch** [comment]
I found the problem. My company's VPN blocked the traffic.
